if (NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE is required.")
endif()

if (NOT DEFINED INCLUDE_ROOT)
    message(FATAL_ERROR "INCLUDE_ROOT is required.")
endif()

set(header_paths "")
if (DEFINED HEADER_PATHS AND NOT HEADER_PATHS STREQUAL "")
    string(REPLACE "||" ";" header_paths "${HEADER_PATHS}")
endif()

set(generated_includes "")
set(register_calls "")
set(unregister_calls "")

foreach(content_header_path IN LISTS header_paths)
    file(RELATIVE_PATH content_header "${INCLUDE_ROOT}" "${content_header_path}")
    file(READ "${content_header_path}" content_header_contents)

    set(symbol_prefix "")
    if (content_header_contents MATCHES "ScriptName[ \t\r\n]*=[ \t\r\n]*\"([^\"]+)\"")
        set(content_name "${CMAKE_MATCH_1}")
        string(FIND "${content_name}" "::" last_namespace_separator REVERSE)
        if (NOT last_namespace_separator EQUAL -1)
            string(SUBSTRING "${content_name}" 0 ${last_namespace_separator} content_namespace)
            set(symbol_prefix "${content_namespace}::")
        endif()
    elseif (content_header_contents MATCHES "namespace[ \t\r\n]+([A-Za-z_][A-Za-z0-9_:]*)[ \t\r\n]*\\{")
        set(symbol_prefix "${CMAKE_MATCH_1}::")
    endif()

    set(header_register_calls "")
    set(header_unregister_calls "")

    foreach(content_kind IN ITEMS Script Component System)
        set(register_matches "")
        set(unregister_matches "")
        set(register_names "")
        set(unregister_names "")

        string(REGEX MATCHALL "Register[A-Za-z_][A-Za-z0-9_]*${content_kind}[ \t\r\n]*\\(" register_matches "${content_header_contents}")
        string(REGEX MATCHALL "UnRegister[A-Za-z_][A-Za-z0-9_]*${content_kind}[ \t\r\n]*\\(" unregister_matches "${content_header_contents}")

        foreach(register_match IN LISTS register_matches)
            string(REGEX REPLACE "[ \t\r\n]*\\(" "" register_name "${register_match}")
            list(APPEND register_names "${register_name}")
        endforeach()

        foreach(unregister_match IN LISTS unregister_matches)
            string(REGEX REPLACE "[ \t\r\n]*\\(" "" unregister_name "${unregister_match}")
            list(APPEND unregister_names "${unregister_name}")
        endforeach()

        list(REMOVE_DUPLICATES register_names)
        list(REMOVE_DUPLICATES unregister_names)

        foreach(register_name IN LISTS register_names)
            string(REGEX REPLACE "^Register" "UnRegister" unregister_name "${register_name}")
            list(FIND unregister_names "${unregister_name}" unregister_index)
            if (unregister_index EQUAL -1)
                continue()
            endif()

            list(APPEND header_register_calls "    ${symbol_prefix}${register_name}(_app)")
            list(APPEND header_unregister_calls "    ${symbol_prefix}${unregister_name}(_app)")
        endforeach()
    endforeach()

    if (header_register_calls OR header_unregister_calls)
        list(APPEND generated_includes "#include <${content_header}>")
        list(APPEND register_calls ${header_register_calls})
        list(APPEND unregister_calls ${header_unregister_calls})
    endif()
endforeach()

list(REMOVE_DUPLICATES generated_includes)
list(REMOVE_DUPLICATES register_calls)
list(REMOVE_DUPLICATES unregister_calls)
list(SORT generated_includes)
list(SORT register_calls)
list(SORT unregister_calls)

set(generated_includes_text "")
foreach(generated_include IN LISTS generated_includes)
    string(APPEND generated_includes_text "${generated_include}\n")
endforeach()

set(register_calls_text "")
foreach(register_call IN LISTS register_calls)
    string(APPEND register_calls_text "${register_call};\n")
endforeach()

set(unregister_calls_text "")
foreach(unregister_call IN LISTS unregister_calls)
    string(APPEND unregister_calls_text "${unregister_call};\n")
endforeach()

set(generated_source
"// This file is generated by CMake. Do not edit by hand.
#pragma once

${generated_includes_text}

inline void RegisterGeneratedGameContent(Canis::App &_app)
{
${register_calls_text}}

inline void UnRegisterGeneratedGameContent(Canis::App &_app)
{
${unregister_calls_text}}

inline void RegisterGeneratedScripts(Canis::App &_app)
{
    RegisterGeneratedGameContent(_app);
}

inline void UnRegisterGeneratedScripts(Canis::App &_app)
{
    UnRegisterGeneratedGameContent(_app);
}
")

if (EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" existing_source)
else()
    set(existing_source "")
endif()

if (NOT existing_source STREQUAL generated_source)
    file(WRITE "${OUTPUT_FILE}" "${generated_source}")
endif()
